server:
  port: 8091
  servlet:
    context-path: /insurance
requestVO:
  #  msgid: 0
  mdtrtarea_admvs: 500155
  #  recer_sys_code: 2
  fixmedins_code: H50015501017
  fixmedins_name: 重庆市梁平区妇幼保健院
  infver: 1
  url: http://localhost:8097/fsi/api/rsfComIfsService/callService
  operateNo: '846'
  operateName: 管理员
  operateType: 1
  serv_code: A6B3720544049E1397
  serv_sign: HH00001

#国家医生代码字段名称
doctorCode: doctor_no
#inp_bill_detail 医院自费项目标志
selfFlag: ''
# newBornFlag 母亲新生儿费用合并上传支持 1，支持 0 不支持
newBornFlag: 0
#对账
checkAcctDettail:
  queryUpload: setl_id,mdtrt_id,psn_no,medfee_sumamt,fund_pay_sumamt,acct_pay,refd_setl_flag

upload:
  startdate: 2021-08-01 00:00:00
  enddate: 2021-10-01 00:00:00

#特殊交易列表
specialBusiness:
  readCard: 1101,1161,1162

spring:
  datasource:
    #梁平测试库
    url: jdbc:oracle:thin:@192.168.22.78:1521:test1
    username: system
    password: manager
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**

logging:
  level:
    root: info

mybatis:
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    jdbc-type-for-null: 'null'
    callSettersOnNulls: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      field-strategy: not_null
      column-like: true
      logic-delete-value: -1
      logic-not-delete-value: 0


