server:
  port: 8091
  servlet:
    context-path: /insurance
requestVO:
  #  msgid: 0
  mdtrtarea_admvs: 500106
  #  recer_sys_code: 2
  fixmedins_code: H50010601566
  fixmedins_name: 重庆市公共卫生医疗救治中心
  infver: 1
  url: http://localhost:8097/fsi/api/rsfComIfsService/callService
  operateNo: '000003'
  operateName: admin
  operateType: 1
spring:
  datasource:
    #公卫正式库
    url: jdbc:oracle:thin:@172.16.2.1:1521:orcl
    username: system
    password: manager
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1 FROM DUAL
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**

logging:
  level:
    root: info

mybatis:
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    jdbc-type-for-null: 'null'
    callSettersOnNulls: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      field-strategy: not_null
      column-like: true
      logic-delete-value: -1
      logic-not-delete-value: 0


